version: 0.1

# Хранилище
storage:
  filesystem:
    rootdirectory: /var/lib/registry

# Логи (по желанию)
log:
  fields:
    service: registry

# HTTP + CORS + TLS
http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control', 'Content-Type', 'X-Requested-With']
