services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5005:5000
    volumes:
      - ./registry:/var/lib/registry
      - ./sert:/certs
      - ./config.yml:/etc/docker/registry/config.yml:ro
  ui:
    build: .
    ports:
      - "8888:3000"
    environment:
      REGISTRY_URL: ${REGISTRY_URL}

